import "./globals.css";

export const metadata = {
  title: "ورزش روز",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl" className={`h-full antialiased`}>
      <body className="min-h-full flex flex-col bg-gray-200">{children}</body>
    </html>
  );
}
