import "./globals.css";
import localFont from "next/font/local";

const estedadFont = localFont({
  src: "./fonts/Estedad[wght,kshd].woff2",
  variable: "--font-persian",
});

export const metadata = {
  title: "ورزش روز",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="fa"
      dir="rtl"
      className={`h-full antialiased ${estedadFont.variable}`}
    >
      <body className="min-h-full flex flex-col bg-gray-200">{children}</body>
    </html>
  );
}
